Conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace="users")),
    path('blogs/',include('blogs.urls',namespace='blogs')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/',include('products.urls',namespace="products")),
    path('',include('pages.urls',namespace='pages')),
    
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('contact/',views.ContactCreateView.as_view(),name='contact'),
    path('about/',views.AboutView.as_view(),name='about'),
    path('home/',views.home_page_view,name='home'),
    path('',views.main_page_view,name='main')
]

templates/pages/about.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}
{% block body %} id="about-us" class="blog" {% endblock %}

{% block content %}
<div class="main-content">
	<div id="wrapper-site">
		<div id="content-wrapper">
			
			<!-- breadcrumb -->
			<nav class="breadcrumb-bg">
				<div class="container no-index">
					<div class="breadcrumb">
						<ol>
							<li>
								<a href="#">
									<span>Home</span>
								</a>
							</li>
							<li>
								<a href="#">
									<span>About us</span>
								</a>
							</li>
						</ol>
					</div>
				</div>
			</nav>
			<div id="main">
				<div class="page-home">
					<div class="container">
						<div class="about-us-content">
							
							<h1 class="title-page">{% trans 'About Us' %}</h1>
							<div class="row">
								<div class="col-lg-6 col-md-6 col-sm-6 right">
									<a href="#">
										<img class="img-fluid" src="{% static 'img/other/1.jpg' %}" alt="#" />
									</a>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 left">
									<div class="cms-block f-right">
										<h3 class="page-subheading">{% trans 'WHO WE ARE' %}</h3>
										<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis biben
											dum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis
											sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
										amet nibh vultate cursus a sit amet mauris.</p>
										<p>Proin gravida nibh vel velit auctor aliquet. nec sagittis sem nibh id elit. Duis
											sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
										amet nibh vultate cursus a sit amet mauris.</p>
										<a>
											<img class="img-fluid" src="{% static 'img/other/4.png' %}" alt="#" />
											<span>Mr. kwang shang - CEO</span>
										</a>
									</div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 right">
									<div class="cms-block f-left">
										<h3 class="page-subheading">{% trans 'WHAT WE DO' %}</h3>
										<p>Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis biben
											dum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis
											sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
										amet nibh vultate cursus a sit amet mauris.</p>
										<p>Proin gravida nibh vel velit auctor aliquet, nec sagittis sem nibh id elit. Duis
											sed odio sit amet nibh vultate cursus a sit amet mauris. Duis sed odio sit
										amet nibh vultate cursus a sit amet mauris.</p>
									</div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 left">
									<a href="#">
										<img class="img-fluid" src="{% static 'img/other/2.jpg' %}" alt="#" />
									</a>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 right">
									<a href="#">
										<img class="img-fluid" src="{% static 'img/other/3.jpg' %}" alt="#" />
									</a>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 left">
									<div class="cms-block f-right">
										<h3 class="page-subheading no-before">{% trans 'MEET OUR TEAM' %}</h3>
										<div class="testimonials owl-carousel owl-theme owl-loaded owl-drag">
											{% for post in posts %}
												<div class="item">
													<div class="name">{{ post.name }}</div>
													<div class="position">{{ post.job }}</div>
													<p>{{ post.description }}
													</p>
												</div>
											{% endfor %}
											
										</div>
										<div class="social-content">
											<div class="social">
												<ul class="list-inline mb-0 justify-content-end">
													<li class="list-inline-item mb-0">
														<a href="#" target="_blank">
															<i class="fa fa-facebook"></i>
														</a>
													</li>
													<li class="list-inline-item mb-0">
														<a href="#" target="_blank">
															<i class="fa fa-twitter"></i>
														</a>
													</li>
													<li class="list-inline-item mb-0">
														<a href="#" target="_blank">
															<i class="fa fa-google"></i>
														</a>
													</li>
													<li class="list-inline-item mb-0">
														<a href="#" target="_blank">
															<i class="fa fa-instagram"></i>
														</a>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/pages/contact.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block body %} id="contact" class="blog" {% endblock %}

{% block content %}

{% for msg in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>{{ msg }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
{% endfor %}

<div class="main-content">
    <div id="wrapper-site">
        <div id="content-wrapper">

            <!-- breadcrumb -->
            <nav class="breadcrumb-bg">
                <div class="container no-index">
                    <div class="breadcrumb">
                        <ol>
                            <li>
                                <a href="#">
                                    <span>Home</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>Contact</span>
                                </a>
                            </li>
                        </ol>
                    </div>
                </div>
            </nav>
            <div id="main">
                <div class="page-home">
                    <div class="container">
                        <h1 class="text-center title-page">{% trans 'Contact Us' %}</h1>
                        <div class="row-inhert">
                            <div class="header-contact">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-4 col-md-4">
                                        <div class="item d-flex">
                                            <div class="item-left">
                                                <div class="icon">
                                                    <i class="zmdi zmdi-email"></i>
                                                </div>
                                            </div>
                                            <div class="item-right d-flex">
                                                <div class="title">Email:</div>
                                                <div class="contact-content">
                                                    <a href="mailto:support@domain.com">support@domain.com</a>
                                                    <br>
                                                    <a href="mailto:contact@domain.com">contact@domain.com</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-4 col-md-4">
                                        <div class="item d-flex">
                                            <div class="item-left">
                                                <div class="icon">
                                                    <i class="zmdi zmdi-home"></i>
                                                </div>
                                            </div>
                                            <div class="item-right d-flex">
                                                <div class="title">Address:</div>
                                                <div class="contact-content">
                                                    23 Suspendis matti, Visaosang Building
                                                    <br>District, NY Accums, North American
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-xs-12 col-sm-4 col-md-4">
                                        <div class="item d-flex justify-content-end  last">
                                            <div class="item-left">
                                                <div class="icon">
                                                    <i class="zmdi zmdi-phone"></i>
                                                </div>
                                            </div>
                                            <div class="item-right d-flex">
                                                <div class="title">Hotline:</div>
                                                <div class="contact-content">
                                                    0123-456-78910
                                                    <br>0987-654-32100
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="contact-map">
                                <div id="map">
                                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.3785754726428!2d105.78134315594316!3d21.01753304734255!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x313454ab43c0c4db%3A0xdb6effebd6991106!2sKeangnam+Hanoi+Landmark+Tower!5e0!3m2!1svi!2s!4v1530175498947" allowfullscreen></iframe>
                                </div>
                            </div>
                            <div class="input-contact">
                                <p class="text-intro text-center">“Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin, lorem quis bibendum
                                    auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit
                                    amet nibh vultate cursus a sit amet mauris. Proin gravida nibh vel velit auctor aliquet.”
                                </p>
                                
                                <p class="icon text-center">
                                    <a href="#">
                                        <img src="{% static 'img/other/contact_mess.png' %}" alt="img">
                                    </a>
                                </p>

                                <div class="d-flex justify-content-center">
                                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                                        <div class="contact-form">
                                            <form action="{% url 'pages:contact' %}" method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="form-fields">
                                                    <div class="form-group row">
                                                        <div class="col-md-6">
                                                            <input class="form-control" name="name" placeholder="{% trans 'Your name' %}">
                                                        </div>
                                                        <div class="col-md-6 margin-bottom-mobie">
                                                            <input class="form-control" name="email" type="email" value="" placeholder="{% trans 'Your email' %}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <div class="col-md-12 margin-bottom-mobie">
                                                            <input class="form-control" name="subject" type="text" value="" placeholder="{% trans 'Subject' %}">
                                                        </div>
                                                    </div>
                                                    <div class="form-group row">
                                                        <div class="col-md-12">
                                                            <textarea class="form-control" name="message" placeholder="{% trans 'Message' %}" rows="8"></textarea>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div>
                                                    <button class="btn" type="submit" name="submitMessage">
                                                        <img class="img-fl" src="{% static 'img/other/contact_email.png' %}" alt="img">{% trans 'Send message' %}
                                                    </button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}