Conf/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace="users")),
    path('blogs/',include('blogs.urls',namespace='blogs')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('products/',include('products.urls',namespace="products")),
    path('',include('pages.urls',namespace='pages')),
    
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path


from blogs import views


app_name = 'blogs'

urlpatterns = [
    path('',views.BlogListView.as_view(),name='blog'),
    path('blog/<int:pk>/',views.BlogDetailView.as_view(),name='blog_detail'),
]

blogs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _

from common.models import BaseModel

UserModel = get_user_model()


class BlogCategoryModel(BaseModel):
    title = models.CharField(max_length=128, verbose_name=_('title'))
    parent = models.ForeignKey(
        'self', on_delete=models.PROTECT,
        null=True, blank=True,
        related_name='children',
        verbose_name=_('parent')
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('blog category')
        verbose_name_plural = _('blog categories')


class BlogTagModel(BaseModel):
    title = models.CharField(max_length=128, verbose_name=_('title'))

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('blog tag')
        verbose_name_plural = _('blog tags')


class BlogAuthorModel(BaseModel):
    first_name = models.CharField(max_length=128, verbose_name=_('first_name'))
    last_name = models.CharField(max_length=128, verbose_name=_('last_name'))
    avatar = models.ImageField(upload_to='blogs/authors/', verbose_name=_('avatar'))

    @property
    def full_name(self):
        return self.__repr__()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def __repr__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = _('blog author')
        verbose_name_plural = _('blog authors')


class BlogModel(BaseModel):
    image = models.ImageField(upload_to='blogs', verbose_name=_('image'))
    title = models.CharField(max_length=128, verbose_name=_('title'))
    description = models.TextField(verbose_name=_('description'))

    authors = models.ManyToManyField(
        BlogAuthorModel,
        related_name='blogs',
        verbose_name=_('authors')
    )
    categories = models.ManyToManyField(
        BlogCategoryModel,
        related_name='blogs',
        verbose_name=_('categories')
    )

    tags = models.ManyToManyField(
        BlogTagModel,
        related_name='tags',
        verbose_name=_('tags')
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('blog')
        verbose_name_plural = _('blogs')


class BlogCommentModel(BaseModel):
    comment = models.CharField(max_length=128, verbose_name=_('comment'))
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        related_name='blog_comments',
        verbose_name=_('user')
    )
    blog = models.ForeignKey(
        BlogModel,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name=_('blog')
    )

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = _('blog comment')
        verbose_name_plural = _('blog comments')

blogs/views.py
from typing import Any
from django.shortcuts import redirect,render
from django.views.generic import ListView,DetailView
from django.db.models import Q


from blogs import models


class BlogListView(ListView):
    template_name = 'blogs/blog.html'
    model = models.BlogModel
    context_object_name = 'blogs'
    paginate_by = 1

    def get_queryset(self):
        blogs = models.BlogModel.objects.all()
        cat = self.request.GET.get('cat')
        tag = self.request.GET.get('tag')
        q = self.request.GET.get('q')
        
        if cat:
            blogs = blogs.filter(categories=cat)
        if tag:
            blogs = blogs.filter(tags=tag)
        if q:
            blogs = blogs.filter(
                Q(title__icontains=q) | Q(description__icontains=q)
            )
       
        return blogs

    def get_context_data(self,*,object_list=None, **kwargs):

        context = super().get_context_data(**kwargs)
        context['categories'] = models.BlogCategoryModel.objects.all()
        context['tags'] = models.BlogTagModel.objects.all()
        context['comments'] = models.BlogCommentModel.objects.all()
        return context


class BlogDetailView(DetailView):
    
    model = models.BlogModel
    template_name = "blogs/blog_detail.html"
    context_object_name = "blog"

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['all_blogs'] = models.BlogModel.objects.all()
        context['categories'] = models.BlogCategoryModel.objects.all()
        context['tags'] = models.BlogTagModel.objects.all()
        context['comments'] = models.BlogCommentModel.objects.filter(blog=self.object)

        return context
    
    def post(self, request, *args, **kwargs):
        pass

templates/blogs/blog.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load i18n %}

{% block body %} id="blog-list-sidebar-left" class="blog" {% endblock %}
{% block content %}
<div class="main-content">
    <div id="wrapper-site">
        <div id="content-wrapper">
            <div id="main">
                <div class="page-home">

                    <!-- breadcrumb -->
                    <nav class="breadcrumb-bg">
                        <div class="container no-index">
                            <div class="breadcrumb">
                                <ol>
                                    <li>
                                        <a href="#">
                                            <span>Home</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span>Living Room</span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <span>Sofa</span>
                                        </a>
                                    </li>
                                </ol>
                            </div>
                        </div>
                    </nav>
                    <div class="container">
                        <div class="content">
                            <div class="row">
                                
                                <div class="col-sm-8 col-lg-9 col-md-9 flex-xs-first main-blogs">
                                    <h2>{% trans 'Recent Posts' %}</h2>
                                    {% for blog in blogs %}
                                        <div class="list-content row">
                                            <div class="hover-after col-md-5 col-xs-12">
                                                <a href="{% url 'blogs:blog_detail' pk=blog.id %}">
                                                    <img src="{{ blog.image.url }}" alt="img">
                                                </a>
                                            </div>
                                            <div class="late-item col-md-7 col-xs-12">
                                                <p class="content-title">
                                                    <a href="{% url 'blogs:blog_detail' pk=blog.id %}">{{ blog.title }}</a>
                                                </p>
                                                <p class="post-info">
                                                    <span>{{ blog.created_at }}</span>
                                                    
                                                    <span>{{ blog.comments.count }} comment</span>
                                                    
                                                    {% for b_a in blog.authors.all %}
                                                        <span>{{ b_a.first_name }}</span>
                                                    {% endfor %}
                                                </p>
                                                <p class="description">{{ blog.description|slice:'150' }}
                                                </p>
                                                <span class="view-more">
                                                    <a href="{% url 'blogs:blog_detail' pk=blog.id %}">{% trans 'view more' %}</a>
                                                </span>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    <nav aria-label="Sahifalar">
                                        <ul class="pagination">
                                            {% if page_obj.has_previous %}
                                                <li><a onclick="addUrlParameter('page',{{ 1 }})">«</a></li>
                                                <li><a onclick="addUrlParameter('page',{{ page_obj.previous_page_number }})">‹</a></li>
                                            {% endif %}
                                    
                                            {% for page in page_obj.paginator.page_range %}
                                                <li class="{% if page == page_obj.number %}active{% endif %}">
                                                    <a onclick="addUrlParameter('page',{{ page }})">{{ page }}</a>
                                                </li>
                                            {% endfor %}
                                    
                                            {% if page_obj.has_next %}
                                                <li><a onclick="addUrlParameter('page',{{ page_obj.next_page_number }})">›</a></li>
                                                <li><a onclick="addUrlParameter('page',{{ page_obj.paginator.num_pages }})">»</a></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>

                                <div class="sidebar-3 sidebar-collection col-lg-3 col-md-3 col-sm-4">

                                    <!-- category -->
                                    <div class="sidebar-block">
                                        <div class="title-block">{% trans 'Categories' %}</div>
                                        <div class="block-content">
                                            {% for category in categories %}
                                                {% if category.parent %}
                                                {% else %}
                                                    <div class="cateTitle hasSubCategory open level1">
                                                        <span class="arrow collapse-icons collapsed" data-toggle="collapse" data-target="#{{ category.id }}" aria-expanded="false" role="status">
                                                            <i class="zmdi zmdi-minus"></i>
                                                            <i class="zmdi zmdi-plus"></i>
                                                        </span>
                                                        
                                                        <a class="cateItem" onclick="addUrlParameter('cat', {{ category.id }})">{{ category.title }}</a>
                                                        
                                                        <div class="subCategory collapse" id="{{ category.id }}" aria-expanded="true" role="status">
                                                            {% for child in category.children.all %}
                                                                <div class="cateTitle">
                                                                    
                                                                    <a onclick="addUrlParameter('cat', {{ child.id }})" class="cateItem">{{ child }}</a>
                                                                    
                                                                </div>
                                                            {% endfor %}
                                                            
                                                        </div>
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                            
                                        </div>
                                    </div>

                                    <!-- recent posts -->
                                    <div class="sidebar-block">
                                        <div class="title-block">{% trans 'Recent Posts' %}</div>
                                        <div class="post-item-content">
                                            <div>
                                                {% for blog in blogs %}
                                                    <div class="late-item first-child">
                                                        <a href="{% url 'blogs:blog_detail' pk=blog.id %}">
                                                            <p class="content-title">{{ blog.title|slice:'15' }}...
                                                                
                                                            </p>
                                                        </a>
                                                        <span>
                                                                <i class="zmdi zmdi-comments"></i>{{ blog.comments.count }} comment
                                                        </span>
                                                        <span>
                                                            <i class="zmdi zmdi-calendar-note"></i>{{ blog.created_at }}
                                                        </span>
                                                        <p class="description">{{ blog.description|slice:'30' }}...
                                                        </p>
                                                        <p class="remove">
                                                            <a href="{% url 'blogs:blog_detail' pk=blog.id %}">READ MORE</a>
                                                        </p>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>

                                    <!-- product tag -->
                                    <div class="sidebar-block product-tags">
                                        <div class="title-block">
                                            {% trans 'Blog Tags' %}
                                        </div>
                                        <div class="block-content">
                                            <ul class="listSidebarBlog list-unstyled">
                                                {% for tag in tags %}
                                                    <li>
                                                        <a onclick="addUrlParameter('tag', {{ tag.id }})" title="{{ tag.title }}">{{ tag.title }}</a>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>

                                    <!-- advertising -->
                                    <div class="sidebar-block group-image-special">
                                        <div class="effect">
                                            <a href="#">
                                                <img class="img-fluid" src="{% static 'img/blog/advertising.jpg' %}" alt="banner-2" title="banner-2">
                                            </a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}
    <script>
        function addUrlParameter(name, value) {
            let searchParams = new URLSearchParams(window.location.search)
            if (searchParams.has(name) && searchParams.get(name) == value) {
                searchParams.delete(name)
            } else {
                searchParams.set(name, value)
            }
            window.location.search = searchParams.toString()
        }
    </script>
{% endblock %}